name: Deploy via FTP

on:
  push:
    branches:
      - main  # o el branch que uses

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /visualizando/quieneson/  # o el subdirectorio que corresponda